"""Test constants to avoid magic values in test files."""

# WESAD surrogate constants
SURROGATE_SEED = 42
SURROGATE_N_SUBJECTS = 6
SURROGATE_WINDOWS_PER_CLASS = 4
SURROGATE_N_CLASSES = 3
SURROGATE_WINDOWS_PER_SUBJECT = SURROGATE_N_CLASSES * SURROGATE_WINDOWS_PER_CLASS  # 12
SURROGATE_FEATURE_DIM = 11
SURROGATE_FUSION_N_FOLDS = 5
SURROGATE_INT8_N_FOLDS = 3

# WESAD validation thresholds
WESAD_TARGET_ACCURACY = 0.80
WESAD_INT8_MAX_ACCURACY_DROP_PP = 3.0

# XDF validation
XDF_DEFAULT_N_SAMPLES = 1000
XDF_PPG_SAMPLES_64HZ_10S = 640
XDF_ACC_SAMPLES_32HZ_10S = 320

# Clock sync tolerances
SYNC_TIER0_TOLERANCE_MS = 10.0
SYNC_TIER1_TOLERANCE_MS = 1.0
SYNC_DRIFT_PPM_TOLERANCE = 5.0

# Signal quality thresholds
TIER0_SPECTRAL_FLATNESS_MAX = 0.6
TIER0_ALPHA_RATIO_MIN = 0.15
TIER1_SPECTRAL_FLATNESS_MAX = 0.3
TIER1_ALPHA_RATIO_MIN = 0.3

# Tier durations
TIER1_TEST_DURATION_S = 120.0
TIER2_TEST_DURATION_S = 60.0

# Night window
NIGHT_WINDOW_MIN_HOURS = 6.5
NIGHT_WINDOW_MAX_HOURS = 7.5

# HRV/ECG
HR_TOLERANCE_BPM = 2.0
RMSSD_MAE_MS = 5.0
MITBIH_SENSITIVITY_TARGET = 0.996
MITBIH_PPV_TARGET = 0.996

# XDF correction tolerances
XDF_OFFSET_TOLERANCE_S = 0.001
XDF_DRIFT_TOLERANCE_S = 0.02

# Sleep staging
MIN_EPOCHS_FOR_VALIDATION = 100
PER_SUBJECT_KAPPA_FLOOR = 0.65
MIN_SUBJECTS_FOR_CLOSURE = 5

# Motion gate
MOTION_GATE_SQI_MIN = 0.5
MOTION_GATE_MAP_MAX = 0.5
MOTION_GATE_REQUIRED_CONSECUTIVE = 2

# Power budget
DEFAULT_HUB_BATTERY_MAH = 3000.0
DEFAULT_TARGET_LIFETIME_H = 24.0

# Test data
TEST_ECG_HR = 72.0
TEST_ECG_FS = 500.0
TEST_PPG_FS = 64.0
TEST_ACC_FS = 100.0
