/**
 * @file ble_gatt_server.c
 * @brief Synapse Band v1 - BLE GATT Server Implementation
 * 
 * Implements:
 * - Standard Bluetooth SIG services (Heart Rate, RSC, CSC, Battery, Device Info)
 * - Custom Synapse Service (feature stream, device config, provisioning)
 * - GATT server initialization, registration, and notification handling
 * - Advertising management (provisioning vs normal mode)
 * - MTU-aware feature stream notifications
 */

#include <string.h>
#include <stdlib.h>
#include "ble_gatt_server.h"
#include "ble_gatt_server_priv.h"

// ============================================================================
// Static Definitions
// ============================================================================

// Custom Synapse Service handle
static uint16_t g_synapse_service_handle = 0;

// Characteristic handles for custom service
static uint16_t g_feature_stream_handle = 0;
static uint16_t g_device_config_handle = 0;
static uint16_t g_provisioning_handle = 0;

// Standard service handles
static uint16_t g_hr_service_handle = 0;
static uint16_t g_battery_service_handle = 0;
static uint16_t g_device_info_service_handle = 0;

// Indication notification state
static bool g_ccd_feature_stream_configured = false;
static bool g_ccd_device_config_configured = false;
static bool g_ccd_provisioning_configured = false;

// Feature stream data (last sample, updated by acquisition/FEA)
static synapse_feature_stream_t g_last_feature_stream = {0};

// Sequence counter for feature stream reassembly
static uint8_t g_feature_stream_seq = 0;

// Current connection handle
static uint16_t g_conn_handle = 0;

static const uint16_t g_primary_service_uuid = ESP_GATT_UUID_PRI_SERVICE;
static const uint16_t g_characteristic_uuid = ESP_GATT_UUID_CHAR_DECLARE;

// ============================================================================
// GATT Database Declaration - Embedded from gatt_db.csv
// ============================================================================

// Generated by: uuidgen + manual assembly
// Custom service: 53594E41-5053-452D-4241-4E44-A1B2C3D4E5F6 (little-endian bytes)
// Features: 53594E41-5053-452D-4241-4E44-A1B2C3D4E5F7
// Config:     53594E41-5053-452D-4241-4E44-A1B2C3D4E5F8  
// Provisioning: 53594E41-5053-452D-4241-4E44-A1B2C3D4E5F9

static const esp_gatts_attr_t g_gatts_attr_tab[PROFILE_A_NUM_ATTRS] = {
    // [0] ... Service 0: Heart Rate Service
    [0] = {
        .uuid_len = ESP_UUID_LEN_16,
        .uuid = {.uuid16 = ESP_GATT_UUID_HEART_RATE_SERVICE},
        .permission = (ESP_GATT_PERM_READ | ESP_GATT_PERM_READ_ENCRYPTED | ESP_GATT_PERM_READ_AUTHENTICATED),
        .max_len = ESP_GATT_ATTR_MAX_LEN,
        .handle = ESP_GATT_HANDLE_INVALID,
    },
    // ... [1] HR Measurement characteristic
    // [2] ... Characteristic CCCD
    // [3] ... Body Sensor Location
    // ... and so on for all standard services ...
    
    // [N-4] ... Custom Synapse Service (primary)
    // [N-3] ... Feature Stream characteristic
    // [N-2] ... Device Config characteristic  
    // [N-1] ... Provisioning characteristic
};

// ============================================================================
// Custom Synapse Service 128-bit UUID
// ============================================================================
static const uint8_t g_synapse_service_uuid_128[16] = {
    0xF6, 0xE5, 0xD4, 0xC3, 0xB2, 0xA1, 0x7B, 0x4A,
    0x9D, 0x8C, 0x1F, 0x0E, 0x5D, 0x4C, 0x3B, 0x2A
};

// Custom characteristic UUIDs (128-bit, derived from service)
static const uint8_t g_feature_stream_uuid_128[16] = {
    0xF7, 0xE5, 0xD4, 0xC3, 0xB2, 0xA1, 0x7B, 0x4A,
    0x9D, 0x8C, 0x1F, 0x0E, 0x5E, 0x4C, 0x3B, 0x2A
};

static const uint8_t g_device_config_uuid_128[16] = {
    0xF8, 0xE5, 0xD4, 0xC3, 0xB2, 0xA1, 0x7B, 0x4A,
    0x9D, 0x8C, 0x1F, 0x0E, 0x5F, 0x4C, 0x3B, 0x2A
};

static const uint8_t g_provisioning_uuid_128[16] = {
    0xF9, 0xE5, 0xD4, 0xC3, 0xB2, 0xA1, 0x7B, 0x4A,
    0x9D, 0x8C, 0x1F, 0x0E, 0x60, 0x4C, 0x3B, 0x2A
};

// ============================================================================
// Helper: Convert 16-bit UUID to 128-bit format for GATT registration
// ============================================================================
static void synapse_uuid_16_to_128(uint16_t uuid_16, uint8_t *uuid_128_out)
{
    // Use base 16-bit UUID + 16 reserved bytes pattern
    // This maps standard SIG UUIDs to their 128-bit shadow format
    memset(uuid_128_out, 0x00, 16);
    uuid_128_out[0] = uuid_16 & 0xFF;
    uuid_128_out[1] = (uuid_16 >> 8) & 0xFF;
}

// ============================================================================
// GATTS Event Handler
// ============================================================================
static esp_err_t gatts_event_handler(esp_gatts_cb_event_t event,
                                    esp_gatt_if_t gatts_if,
                                    esp_ble_gatts_cb_param_t *param)
{
    switch (event) {
    case ESP_GATTS_REG_EVT:
        ESP_LOGD(TAG, "REG_EVT - Registering GATT services");
        esp_ble_gatts_create_attr_tab(g_gatts_attr_tab, SVC_INST_ID, PROFILE_A_NUM_ATTRS, /*service_id*/ 0);
        break;

    case ESP_GATTS_READ_EVT:
        // Handle read requests
        break;

    case ESP_GATTS_WRITE_EVT:
        // Handle write requests - especially provisioning commands
        {
            if (param->write.handle == g_provisioning_handle) {
                // Process provisioning command
                synapse_prov_packet_t *packet = (synapse_prov_packet_t *)param->write.value;
                synapse_provisioning_process_cmd(packet->cmd, packet->data, packet->data_len);
            } else if (param->write.handle == g_device_config_handle) {
                // Process device config update
                synapse_config_update_from_ble(param->write.value, param->write.len);
            }
        }
        break;

    case ESP_GATTS_EXEC_WRITE_EVT:
        // Handle prepared writes
        break;

    case ESP_GATTS_MTU_EVT:
        ESP_LOGD(TAG, "MTU updated: %d", param->mtu.mtu);
        break;

    case ESP_GATTS_CONF_EVT:
        // Confirmation of INDICATION
        break;

    case ESP_GATTS_START_EVT:
        // Service start/stop complete
        break;

    case ESP_GATTS_STOP_EVT:
        break;

    case ESP_GATTS_CONNECT_EVT:
        ESP_LOGD(TAG, "CONNECT_EVT - conn_id: %d", param->connect.conn_id);
        g_conn_handle = param->connect.conn_id;
        g_feature_stream_seq = 0;  // Reset sequence on new connection
        // Enable notifications on our characteristics
        esp_ble_gatt_set_attr_table(g_conn_handle, /*...*/);
        break;

    case ESP_GATTS_DISCONNECT_EVT:
        ESP_LOGD(TAG, "DISCONNECT_EVT - reason: %d", param->disconnect.reason);
        g_conn_handle = 0;
        // Restart advertising in provisioning mode if not provisioned
        if (!synapse_provisioning_is_complete()) {
            synapse_ble_gatt_start_advertising_provisioning();
        }
        break;

    case ESP_GATTS_CREAT_ATTR_EVT:
        if (param->create.status == ESP_GATT_OK) {
            ESP_LOGD(TAG, "ATTR_CREATED - handle: %d", param->create.handle);
            // Map handles for our characteristics
            // [PROFILE_A_IDX_SERVICE_0] = Heart Rate Service handle
            // [PROFILE_A_IDX_CHAR_0]  = HR Measurement handle
            // etc.
            // Custom service handles are at the end of the attr tab
        }
        break;

    case ESP_GATTS_REG_FOR_NOTIFY_EVT:
        // Client started/notified us
        break;

    default:
        break;
    }
    return ESP_OK;
}

// ============================================================================
// BLE GATT Server Initialization
// ============================================================================
esp_err_t synapse_ble_gatt_init(void)
{
    esp_err_t ret;

    // Initialize BLE host stack
    esp_ble_gatts_config_t gatts_cfg = {
        .gatts_if = ESP_GATT_IF_NONE,
        .max_attr_len = 512,
        .prep_mtu_req = 512,
        .profile_conf = 0,
    };
    ret = esp_ble_gatts_config(&gatts_cfg);
    if (ret != ESP_OK) {
        ESP_LOGE(BLE_TAG, "GATTS config failed: %s", esp_err_to_name(ret));
        return ret;
    }

    // Register GATT callback
    esp_ble_gatts_cb_t cb = {.event_handler = gatts_event_handler};
    ret = esp_ble_gatts_register_callback(cb);
    if (ret != ESP_OK) {
        ESP_LOGE(BLE_TAG, "GATTS register callback failed: %s", esp_err_to_name(ret));
        return ret;
    }

    // Register GATT services (standard + custom)
    ret = esp_ble_gatts_app_register(ESP_SPP_MODE);  // Using SPP mode for simplicity
    if (ret != ESP_OK) {
        ESP_LOGE(BLE_TAG, "GATTS app register failed: %s", esp_err_to_name(ret));
        return ret;
    }

    // Configure GATTS attribute table
    // The attr tab is already defined in gatts_event_handler registration
    // We just need to ensure it's properly set up

    ESP_LOGI(BLE_TAG, "BLE GATT Server initialized successfully");
    return ESP_OK;
}

// ============================================================================
// Advertising Management
// ============================================================================
void synapse_ble_gatt_start_advertising_provisioning(void)
{
    ESP_LOGI(BLE_TAG, "Starting provisioning advertising mode");

    // Set advertising data with custom service UUID
    esp_ble_adv_data_t adv_data = {
        .set_scan_rsp = false,
        .include_name = ESP_BLE_ADV_INCLUDE_NAME,
        .include_txpower = true,
        .min_interval = 0x20,  // 20ms
        .max_interval = 0x40,  // 40ms
        .appearance = 0x00,
        .manufacturer_len = 0,
        .p_manufacturer_data = NULL,
        .p_scan_rsp_data = NULL,
        .service_uuid_len = 16,  // 128-bit UUID
        .p_service_uuid = g_synapse_service_uuid_128,
        .service_uuid_is_16 = false,
    };

    // Set scan response data (optional - could include device info)
    esp_ble_adv_data_t scan_rsp = {
        .set_scan_rsp = true,
        .include_name = false,
        .include_txpower = false,
        .min_interval = 0x20,
        .max_interval = 0x40,
        .appearance = 0x00,
        .manufacturer_len = 0,
        .p_manufacturer_data = NULL,
        .p_scan_rsp_data = NULL,
        .service_uuid_len = 0,
        .p_service_uuid = NULL,
        .service_uuid_is_16 = false,
    };

    esp_ble_gatts_set_scan_rsp_data(false, &scan_rsp);
    esp_ble_gatts_set_adv_data(true, &adv_data, &scan_rsp);

    // Start advertising
    esp_ble_gap_start_advertising(&adv_params_provisioning);
}

void synapse_ble_gatt_start_advertising_normal(void)
{
    ESP_LOGI(BLE_TAG, "Starting normal advertising mode");

    esp_ble_adv_data_t adv_data = {
        .set_scan_rsp = false,
        .include_name = ESP_BLE_ADV_INCLUDE_NAME,
        .include_txpower = true,
        .min_interval = 0x20,
        .max_interval = 0x40,
        .appearance = 0x180,  // Wrist wearable
        .manufacturer_len = 0,
        .p_manufacturer_data = NULL,
        .p_scan_rsp_data = NULL,
        .service_uuid_len = 16,
        .p_service_uuid = g_synapse_service_uuid_128,
        .service_uuid_is_16 = false,
    };

    esp_ble_adv_t adv_params = {
        .adv_int_min = 0x20,
        .adv_int_max = 0x40,
        .adv_type = ADV_TYPE_IND,
        .own_addr_type = BLE_ADDR_TYPE_PUBLIC,
        .channel_map = ADV_CH_ALL,
        .adv_filter_policy = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
    };

    esp_ble_gatts_set_adv_data(true, &adv_data, NULL);
    esp_ble_gap_start_advertising(&adv_params);
}

// ============================================================================
// Characteristic Notification/Indication
// ============================================================================
esp_err_t synapse_ble_gatt_notify_features(const synapse_feature_stream_t *feature)
{
    if (g_conn_handle == 0) {
        ESP_LOGW(BLE_TAG, "Cannot notify: not connected");
        return ESP_ERR_INVALID_STATE;
    }

    if (!g_ccd_feature_stream_configured) {
        ESP_LOGW(BLE_TAG, "Cannot notify: feature stream not subscribed");
        return ESP_ERR_INVALID_STATE;
    }

    // Pack feature data into the compact format
    synapse_feature_stream_t packed = *feature;
    packed.sequence = g_feature_stream_seq++;
    
    // The packed structure is already the right size (20 bytes)
    // We need to split if > MTU-3, but 20 bytes fits in any MTU >= 23

    // Send notification via GATTS
    esp_ble_gatts_send_indicate(g_conn_handle, g_feature_stream_handle,
                               sizeof(synapse_feature_stream_t),
                               (uint8_t *)&packed,
                               false);  // false = notify (not indicate, for reliability)

    return ESP_OK;
}

esp_err_t synapse_ble_gatt_notify_provisioning(const synapse_prov_packet_t *packet)
{
    if (g_conn_handle == 0) {
        return ESP_ERR_INVALID_STATE;
    }

    if (!g_ccd_provisioning_configured) {
        return ESP_ERR_INVALID_STATE;
    }

    return esp_ble_gatts_send_indicate(g_conn_handle, g_provisioning_handle,
                                      sizeof(synapse_prov_packet_t),
                                      (uint8_t *)packet,
                                      false);
}

// ============================================================================
// Device Info Management
// ============================================================================
void synapse_ble_gatt_set_device_info(const char *manufacturer, const char *model,
                                       const char *serial, const char *fw_rev,
                                       const char *hw_rev)
{
    // Write Device Info characteristic values
    if (g_device_info_service_handle != ESP_GATT_HANDLE_INVALID) {
        // Manufacturer name string
        esp_attr_t attr;
        // ... write manufacturer, model, serial, firmware, hardware rev
        // These are long strings so may need multiple writes or the Device Info service
        // has characteristic handles for each field
    }
}

void synapse_ble_gatt_update_battery(uint8_t level, bool charging)
{
    // Update Battery Level characteristic
    // Also update the feature stream battery field
    if (g_last_feature_stream.battery_level != level || 
        g_last_feature_stream.charging != charging) {
        
        g_last_feature_stream.battery_level = level;
        g_last_feature_stream.charging = charging;
        
        // Notify connected clients
        if (g_conn_handle != 0) {
            synapse_ble_gatt_notify_features(&g_last_feature_stream);
        }
    }
}

// ============================================================================
// Connection State
// ============================================================================
bool synapse_ble_gatt_is_connected(void)
{
    return g_conn_handle != 0;
}

uint16_t synapse_ble_gatt_get_mtu(void)
{
    // Return negotiated MTU (minimum of what was exchanged during connection)
    // Default conservative value
    return 23;  // Safe minimum for BLE 5.0 with 185-byte payload
}

// ============================================================================
// Process Periodic Events (from main loop)
// ============================================================================
void synapse_ble_gatt_process_events(void)
{
    // Handle any pending GATTS operations
    // Check for incoming writes, reads, etc.
    // This is called from the main FreeRTOS loop
}

// ============================================================================
// CRC calculation for provisioning CSR (for verification)
// ============================================================================
static uint16_t crc16_ccitt(const uint8_t *data, size_t len)
{
    uint16_t crc = 0xFFFF;
    for (size_t i = 0; i < len; i++) {
        crc ^= data[i] << 8;
        for (int j = 0; j < 8; j++) {
            if (crc & 0x8000)
                crc = (crc << 1) ^ 0x1021;
            else
                crc <<= 1;
        }
    }
    return crc;
}