/**
 * @file model_data.h
 * @brief Embedded TFLM Model Data
 * 
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * Generated by: scripts/quantize_and_deploy.py
 * Contains: stress_triage_int8.tflite as byte array
 * 
 * To regenerate:
 *   python scripts/quantize_and_deploy.py --model stress_triage --output firmware/esp32_band/edge_ai/model_data.h
 */

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

// Stress Triage Model (INT8 quantized, 26 features -> 3 classes)
extern const unsigned char g_triage_model_data[];
extern const unsigned int g_triage_model_data_len;

// Model metadata
#define TRIAGE_MODEL_INPUT_FEATURES  26
#define TRIAGE_MODEL_OUTPUT_CLASSES  3
#define TRIAGE_MODEL_ARENA_SIZE      (64 * 1024)  // 64 KB

#endif // MODEL_DATA_H